"""Initial migration

Revision ID: b29b890c12a6
Revises: 
Create Date: 2025-08-29 11:21:14.358818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b29b890c12a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_dashboard_shares_share_token'), table_name='dashboard_shares')
    op.drop_table('dashboard_shares')
    op.drop_table('widgets')
    op.drop_table('dashboard_versions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('queries')
    op.drop_table('data_sources')
    op.drop_table('query_results')
    op.drop_table('data_source_tests')
    op.drop_index(op.f('ix_dashboards_slug'), table_name='dashboards')
    op.drop_table('dashboards')
    op.drop_table('dashboard_data_sources')
    op.drop_table('user_organizations')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('slug', sa.VARCHAR(), nullable=True),
    sa.Column('domain', sa.VARCHAR(), nullable=True),
    sa.Column('logo_url', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('industry', sa.VARCHAR(), nullable=True),
    sa.Column('size', sa.VARCHAR(), nullable=True),
    sa.Column('settings', sa.VARCHAR(), nullable=True),
    sa.Column('subscription_tier', sa.VARCHAR(), nullable=True),
    sa.Column('subscription_status', sa.VARCHAR(), nullable=True),
    sa.Column('trial_ends_at', sa.DATETIME(), nullable=True),
    sa.Column('max_users', sa.INTEGER(), nullable=True),
    sa.Column('max_dashboards', sa.INTEGER(), nullable=True),
    sa.Column('max_data_sources', sa.INTEGER(), nullable=True),
    sa.Column('max_widgets_per_dashboard', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=1)
    op.create_table('user_organizations',
    sa.Column('user_id', sa.VARCHAR(), nullable=True),
    sa.Column('organization_id', sa.VARCHAR(), nullable=True),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.Column('joined_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('dashboard_data_sources',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('dashboard_id', sa.VARCHAR(), nullable=True),
    sa.Column('data_source_id', sa.VARCHAR(), nullable=True),
    sa.Column('alias', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboards',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('slug', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('owner_id', sa.VARCHAR(), nullable=True),
    sa.Column('organization_id', sa.VARCHAR(), nullable=True),
    sa.Column('config', sa.TEXT(), nullable=True),
    sa.Column('layout', sa.TEXT(), nullable=True),
    sa.Column('theme', sa.VARCHAR(), nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), nullable=True),
    sa.Column('is_template', sa.BOOLEAN(), nullable=True),
    sa.Column('share_token', sa.VARCHAR(), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(), nullable=True),
    sa.Column('tags', sa.TEXT(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('icon', sa.VARCHAR(), nullable=True),
    sa.Column('thumbnail_url', sa.VARCHAR(), nullable=True),
    sa.Column('view_count', sa.INTEGER(), nullable=True),
    sa.Column('star_count', sa.INTEGER(), nullable=True),
    sa.Column('fork_count', sa.INTEGER(), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=True),
    sa.Column('parent_id', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('published_at', sa.DATETIME(), nullable=True),
    sa.Column('last_accessed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['dashboards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_index(op.f('ix_dashboards_slug'), 'dashboards', ['slug'], unique=False)
    op.create_table('data_source_tests',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('data_source_id', sa.VARCHAR(), nullable=True),
    sa.Column('test_type', sa.VARCHAR(), nullable=True),
    sa.Column('test_query', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('response_time', sa.INTEGER(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.Column('tested_by', sa.VARCHAR(), nullable=True),
    sa.Column('tested_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['tested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_results',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('query_id', sa.VARCHAR(), nullable=True),
    sa.Column('data', sa.TEXT(), nullable=True),
    sa.Column('row_count', sa.INTEGER(), nullable=True),
    sa.Column('column_count', sa.INTEGER(), nullable=True),
    sa.Column('execution_time', sa.INTEGER(), nullable=True),
    sa.Column('executed_by', sa.VARCHAR(), nullable=True),
    sa.Column('parameters_used', sa.TEXT(), nullable=True),
    sa.Column('is_cached', sa.BOOLEAN(), nullable=True),
    sa.Column('cache_hit', sa.BOOLEAN(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('organization_id', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('connection_string', sa.TEXT(), nullable=True),
    sa.Column('host', sa.VARCHAR(), nullable=True),
    sa.Column('port', sa.INTEGER(), nullable=True),
    sa.Column('database_name', sa.VARCHAR(), nullable=True),
    sa.Column('schema_name', sa.VARCHAR(), nullable=True),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('password_encrypted', sa.TEXT(), nullable=True),
    sa.Column('api_endpoint', sa.VARCHAR(), nullable=True),
    sa.Column('api_key_encrypted', sa.TEXT(), nullable=True),
    sa.Column('headers', sa.TEXT(), nullable=True),
    sa.Column('auth_type', sa.VARCHAR(), nullable=True),
    sa.Column('ssl_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('connection_timeout', sa.INTEGER(), nullable=True),
    sa.Column('query_timeout', sa.INTEGER(), nullable=True),
    sa.Column('max_rows', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('last_connection_test', sa.DATETIME(), nullable=True),
    sa.Column('last_sync', sa.DATETIME(), nullable=True),
    sa.Column('connection_status', sa.VARCHAR(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('tables_metadata', sa.TEXT(), nullable=True),
    sa.Column('columns_metadata', sa.TEXT(), nullable=True),
    sa.Column('cache_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('cache_ttl', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queries',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('data_source_id', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('query_text', sa.TEXT(), nullable=False),
    sa.Column('query_type', sa.VARCHAR(), nullable=True),
    sa.Column('parameters', sa.TEXT(), nullable=True),
    sa.Column('default_values', sa.TEXT(), nullable=True),
    sa.Column('is_cached', sa.BOOLEAN(), nullable=True),
    sa.Column('cache_key', sa.VARCHAR(), nullable=True),
    sa.Column('estimated_runtime', sa.INTEGER(), nullable=True),
    sa.Column('last_runtime', sa.INTEGER(), nullable=True),
    sa.Column('execution_count', sa.INTEGER(), nullable=True),
    sa.Column('last_executed_at', sa.DATETIME(), nullable=True),
    sa.Column('last_executed_by', sa.VARCHAR(), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=True),
    sa.Column('is_published', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['last_executed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('full_name', sa.VARCHAR(), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), nullable=True),
    sa.Column('timezone', sa.VARCHAR(), nullable=True),
    sa.Column('language', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('email_verified_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=1)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    op.create_table('dashboard_versions',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('dashboard_id', sa.VARCHAR(), nullable=True),
    sa.Column('version_number', sa.INTEGER(), nullable=False),
    sa.Column('config_snapshot', sa.TEXT(), nullable=True),
    sa.Column('widgets_snapshot', sa.TEXT(), nullable=True),
    sa.Column('change_description', sa.TEXT(), nullable=True),
    sa.Column('created_by_id', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widgets',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('dashboard_id', sa.VARCHAR(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('position_x', sa.INTEGER(), nullable=True),
    sa.Column('position_y', sa.INTEGER(), nullable=True),
    sa.Column('width', sa.INTEGER(), nullable=True),
    sa.Column('height', sa.INTEGER(), nullable=True),
    sa.Column('z_index', sa.INTEGER(), nullable=True),
    sa.Column('data_source_id', sa.VARCHAR(), nullable=True),
    sa.Column('query', sa.TEXT(), nullable=True),
    sa.Column('filters', sa.TEXT(), nullable=True),
    sa.Column('aggregation', sa.VARCHAR(), nullable=True),
    sa.Column('group_by', sa.VARCHAR(), nullable=True),
    sa.Column('config', sa.TEXT(), nullable=True),
    sa.Column('style', sa.TEXT(), nullable=True),
    sa.Column('color_scheme', sa.VARCHAR(), nullable=True),
    sa.Column('refresh_interval', sa.INTEGER(), nullable=True),
    sa.Column('is_interactive', sa.BOOLEAN(), nullable=True),
    sa.Column('is_locked', sa.BOOLEAN(), nullable=True),
    sa.Column('warning_threshold', sa.FLOAT(), nullable=True),
    sa.Column('critical_threshold', sa.FLOAT(), nullable=True),
    sa.Column('alert_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboard_shares',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('dashboard_id', sa.VARCHAR(), nullable=True),
    sa.Column('share_type', sa.VARCHAR(), nullable=True),
    sa.Column('share_token', sa.VARCHAR(), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(), nullable=True),
    sa.Column('can_edit', sa.BOOLEAN(), nullable=True),
    sa.Column('can_duplicate', sa.BOOLEAN(), nullable=True),
    sa.Column('can_export', sa.BOOLEAN(), nullable=True),
    sa.Column('allowed_emails', sa.TEXT(), nullable=True),
    sa.Column('allowed_domains', sa.TEXT(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('max_views', sa.INTEGER(), nullable=True),
    sa.Column('current_views', sa.INTEGER(), nullable=True),
    sa.Column('created_by_id', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_accessed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_shares_share_token'), 'dashboard_shares', ['share_token'], unique=1)
    op.create_table('api_keys',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('key_hash', sa.VARCHAR(), nullable=False),
    sa.Column('last_used_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('permissions', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    # ### end Alembic commands ###
